implement react hook form add Form components to users and materials
leotammaro/vasa-client-frontend pull request #6
Opened 2022-10-14 00:15 UTC by leotammaro

2022-10-16 21:44 UTC, tammaroivan submitted a review, later dismissed

2022-10-16 21:44 UTC, tammaroivan commented on src/components/admin/UsersBodyForm.jsx
> +        <Input id="username" placeholder="Ingresar nombre del usuario" />
tiene id por algo en especial?

2022-10-18 22:25 UTC, leotammaro commented on src/components/admin/UsersBodyForm.jsx
> +        <Input id="username" placeholder="Ingresar nombre del usuario" />
Se me pasó por alto, no es necesario. Ahora lo flixeo

2022-10-19 23:26 UTC, tammaroivan requested changes

2022-10-19 23:26 UTC, tammaroivan commented on src/components/admin/Materiales.jsx
> +      children={<MaterialsBodyForm />}
el children se pasa dentro del component

```
<TableFiltering>
  <MaterialsBodyForm />
</TableFiltering>
```

2022-10-20 00:01 UTC, tammaroivan approved these changes

2022-10-20 00:03 UTC, merged